aphid_data<-read.csv(header = T, sep=",", file.choose())
aphid_data
summary(aphid_data)
attach(aphid_data)
detach(aphid_data)
aphid_data$Day<-as.factor(aphid_data$Day)
aphid_data$Treatment<-as.factor(aphid_data$Treatment)
is.factor(aphid_data$Day)
is.factor(aphid_data$Treatment)
summary(aphid_data)
aov1way<-lm(Aphid~Treatment)
anova(aov1way)
plot(aov1way)
aov2way<-lm(Aphid~Treatment*Day)
anova(aov2way)
plot(Aphid~Treatment+Day)
leaf2way<-lm(Leaf~Treatment*Day)
anova(leaf2way)
plot(Aphid~Leaf)
TukeyHSD
aphid_data$Ratio<-as.numeric(aphid_data$Ratio)
summary(aphid_data)
install.packages("dplyr")
install.packages("ggpubr")
a<-aphid_data[-c(198),]
a
summary(a)
aov1way<-(lm(Aphid~Treatment*Day,))
anova(aov1way)
plot(aov1way)
rm(list = ls())
last_day<-aphid_data[c(154:204),]
last_day
last_day_leaf_salt<-lm(Leaf~Treatment, data=last_day)
anova(last_day_leaf_salt)
plot(last_day_leaf_salt)
library("car")
qqPlot(Aphid$aphid_data)
shapiro.test(GrowthRatio[1:17])
shapiro.test(GrowthRatio[18:34])
shapiro.test(GrowthRatio[35:51])
shapiro.test(GrowthRatio[52:68])
shapiro.test(GrowthRatio[69:85])
shapiro.test(Ratio[86:102])
shapiro.test(Ratio[103:119])
shapiro.test(Ratio[120:136])
shapiro.test(Ratio[137:153])
shapiro.test(Ratio[154:170])
shapiro.test(Ratio[171:187])
shapiro.test(Ratio[188:204])
aphid_data
oneway.test(Aphid[154:204]~Treatment, var.equal = TRUE)
welch_anova_test(aphid_data, Aphid~Leaf)
g.test(Aphid, y = NULL, p = rep(1/length(x), length(x)), rescale.p = True)
kruskal.test(Aphid~Day, data=aphid_data)
growth_analysis<-read.csv(header = T, sep=",", file.choose())
attach(growth_analysis)
detach(growth_analysis)
growth_analysis
summary(growth_analysis)
growthfit<-lm(Growth~Day)
avgrowth<-aov(Growth[52:204]~Day[52:204]*Treatment[52:204])
anova(growthfit)
plot(growthfit)
growth_analysis$Day<-as.factor(growth_analysis$Day)
is.factor(Day)
growth_analysis$Treatment<-as.factor(growth_analysis$Treatment)
is.factor(Treatment)
summary(growth_analysis)
TukeyHSD(avgrowth)
growth_analysis$Growth_Ratio<-as.numeric(growth_analysis$Growth_Ratio)
glf<-lm(Growth_Ratio[52:204]~Leaf[52:204])
summary(glf)
plot(glf)
plot(Growth[52:204]~Leaf[52:204])
abline(glf)
lint_roller<-lm(Aphid~Leaf)
summary(lint_roller)
plot(lint_roller)
gr<-aov(Ratio[52:204]~Treatment[52:204]*Day[52:204])
TukeyHSD(gr)
RL<-lm(Growth_Ratio[52:204]~Leaf[52:204])
RL
summary(RL)
plot(RL)
plot(Ratio~Leaf)
abline(RL)
abcdefg<-read.csv(header = T, sep=",", file.choose())
a<-abcdefg
a
attach(a)
line<-lm()
a
gr
library(FSA)
kruskal.test(Growth_Ratio~Treatment)

kruskal.test(Growth_Ratio[1:51]~Treatment[1:51])
dunnTest(Growth_Ratio[1:51]~Treatment[1:51], method="bh")
kruskal.test(Growth_Ratio[52:102]~Treatment[52:102])
dunnTest(Growth_Ratio[52:102]~Treatment[52:102], method="bh")
kruskal.test(Growth_Ratio[103:153]~Treatment[103:153])
dunnTest(Growth_Ratio[103:153]~Treatment[103:153], method="bh")
kruskal.test(Growth_Ratio[154:204]~Treatment[154:204])
dunnTest(Growth_Ratio[154:204]~Treatment[154:204], method="bh")
plot(Growth_Ratio~Leaf)
grl<-lm(Growth_Ratio~Leaf)
abline(grl)
summary(grl)
